import java.util.Random;

public class QRCode {
	
	private static int [][] grid;
	
	//Returns a 1D int array with size of dim squared 
	//Filled with random 0 and 1 generated by javautilRandom object 
	public int [] createPattern (int dim, int seed) {
		Random rand = new Random();
		int [] Array1D = new int [dim];
		for (int i = 0; i < Array1D.length; i++) {
			Array1D[i] = rand.nextInt(seed);
		}
		return Array1D;
	}
	
	//Takes dim dimensions and creates 2D array with size of dim by dim 
	//Grid filled row by row from pattern provided by 1D array pattern passed in 
	public void setGrid (int dim, int [] pattern) {
		
	}
	
	//Returns representation of grid member
	public int [][] getGrid() {
		
	}
	
	//Overwrites existing grid with Finder pattern described here 
	//Places finder in each of upper left, upper right, and lower left corners of grid
	//Returns null if grid is null 
	public void setFinder(int xPos, int yPos) {
		
		
	}
	
	//Outputs class member grid as 2D grid with no spaces between values in a row 
	public void print() {
		
		
	}
	
	//Outputs 1D pattern passed as a parameter as 2D grid with no spaces between values in a row 
	public void print(int [] pattern) {
		
	}
	
	//Outputs 2D matrix passed as a parameter row by row with no sapced between values in a row 
	public void print(int [][] matrix) {
		
	}
	
	public static void main (String [] args) {
		QRCode Code = new QRCode(); 
	}
}
